### ISSUE TITLE
Inscription datatype not always a string

### ISSUE THREAD

**Issue by ralight** [openbenches/openbenches.org#237]
The text for https://openbenches.org/bench/12335 is just '2000'. The API returns this as a number, not a string. That's perfectly valid from a json point of view, but it was a surprise to me and I thought it might be to you as well.

**Comment by edent** [comment]
Interesting. I think it is caused by:

https://github.com/openbenches/openbenches.org/blob/cc4f93fa7733f2df4669ef421fa272f5eb27da72/www/apis/v1.0.data.json.php#L40

IIRC that was to stop weird precision issues from creeping in. And makes sure that the IDs are always an `int`. I'm not sure if I can force `JSON_NUMERIC_CHECK` to apply only to part of the JSON, but I'll check.

Thanks for letting us know :-)
