### ISSUE TITLE
Benches being replaced with entries with fewer pictures

### ISSUE THREAD

**Issue by jrbray1** [openbenches/openbenches.org#264]
My bench total dropped by 10 last night, I think because benches I had in Greenwich Park are being replaced/updated with ones submitted by endim8. I don't have a problem with updates, but the new entries often only have 1 or 2 photos, while I'm sure mine had 3. Does the duplicate spotting algorithm just delete the older version, rather than prompt for the entries to be merged to preserve the best of both? 

Endim8 seems to have visited the Rose Garden like me, and added a few benches, but mostly tidied text/positions, but that removes the credit from jenblacker who often originally created the entries, and me who added extra ones. It seems petty for me to go back and move the position a few feet just to reclaim it for my total, especially if it knocked down endim8's numbers

**Comment by endim8** [comment]
Oh dear, I do remember trying to tidy up the Rose Garden & accidentally deleting a few benches because I assumed they'd been removed, only to find them in another location later.

There should definitely be a better duplicate-management system, ideally if the text is very similar it could warn of a similar bench nearby, and suggest moving it to the new position?

Really sorry about the deletions :(

**Comment by edent** [comment]
Do you know which ones you deleted? I can reinstate them?

I think, for now, I'll remove the "delete" button and keep that admin only. That should prevent those issues.

**Comment by jrbray1** [comment]
I have used the delete button occasionally when I've mucked up, but a
comment you can read is equally good, so admin only seems sensible.
