### ISSUE TITLE
suggestion: show a list of available tags to add

### ISSUE THREAD

**Issue by backache** [openbenches/openbenches.org#282]
Though I can add a tag at creation time, I don't know what the valid ones are perhaps a tag-cloud or even a multi-select dropdown would be good.

by encouraging tagging you could pass them though to the twitter entry as a hashtag

Could we also have a link on the frontpage to page listing them to encourage exploring?

For example if anytone would like an explore, the current list of tags are as follows (I have made them into links)

[18th Century](https://openbenches.org/tag/18th_Century)
[19th Century](https://openbenches.org/tag/19th_Century)
[beach](https://openbenches.org/tag/beach)
[cat](https://openbenches.org/tag/cat)
[colleague](https://openbenches.org/tag/colleague)
[dog](https://openbenches.org/tag/dog)
[emoji](https://openbenches.org/tag/emoji)
[famous](https://openbenches.org/tag/famous)
[funny](https://openbenches.org/tag/funny)
[graveyard](https://openbenches.org/tag/graveyard)
[illegible](https://openbenches.org/tag/illegible)
[indoors](https://openbenches.org/tag/indoors)
[metal](https://openbenches.org/tag/metal)
[multiple plaques](https://openbenches.org/tag/multiple_plaques)
[park](https://openbenches.org/tag/park)
[picture](https://openbenches.org/tag/picture)
[poem](https://openbenches.org/tag/poem)
[quote](https://openbenches.org/tag/quote)
[statue](https://openbenches.org/tag/statue)
[stone](https://openbenches.org/tag/stone)
[train station](https://openbenches.org/tag/train_station)
[twinned](https://openbenches.org/tag/twinned)
[wood](https://openbenches.org/tag/wood)

**Comment by arizonagroovejet** [comment]
On https://openbenches.org/add/ click in the text field next to "Choose some tags:" and a list appears which can be scrolled through. That is all the valid tags. So that's how you know what the valid tags are. Or maybe I don't understand the problem you're describing.

I like the idea of a list of tags somewhere easily viewable for people to click on and explore but based on the number mentioned [in this comment ](https://github.com/openbenches/openbenches.org/issues/281#issuecomment-1368210583 )  roughly 6% of benches have tags which means the feature wouldn't be all that useful. Perhaps there could be a big tagathon. No idea how that would work. :smile:

**Comment by backache** [comment]
Yes a virtual tagathon  by perhaps downloading the database using that to work out some commonalities and doing bulk  inserts based on them.

The could then have another use that if a bench is shared, the tags are included in the text with hash's in front of them, in effect making route back to openbenches for some interested in "cricket" for example

**Comment by edent** [comment]
Add page now makes tagging more obvious. Editing a bench allows you to add or remove tags.

![Screenshot showing a bunch of checkboxes.](https://github.com/openbenches/openbenches.org/assets/837136/1d32b8ba-f8f5-4f4a-9105-d6e05b55f230)
