### ISSUE TITLE
Make finding a bench already "bagged" a positive thing

### ISSUE THREAD

**Issue by backache** [openbenches/openbenches.org#383]
Came across a bench that had already been "bagged" yesterday.

I wonder if we can make that a positive giving-back experience by us being able to do things like a one-click verification that it is still there, a good entry or perhaps even adding more data/tags, it would mean also been by getting more data with geographic coordinates the location is further verified by triangulating the various entries.  

I was also thinking that for benches without anything on them we can mark them as such so that when comparing openstreet maps database and ours it doesn't look like it hasn't been visited.

**Comment by edent** [comment]
You can click "Edit this bench". That will allow you to add more photos and tags. You can also adjust the location and correct the inscription.

There isn't a delete button there - but people can and do leave comments to say if a bench is missing.

People quite often add duplicate entries. I get an alert and merge them if necessary. 

For example, you added a bench recently which I merged with an existing one - see https://openbenches.org/bench/19184 which has your photo and someone else's.

Finally, as for "naked benches", I'm not quite sure I understand what you're proposing. I don't think we want to add *every* bench in the world - only those with inscriptions. So I wouldn't want to clutter our DB with blank benches.

Perhaps it would make sense for you to add a tag to OSM? `memorial=no` or similar - https://wiki.openstreetmap.org/wiki/Tag:amenity=bench?uselang=en-GB#Tags_used_in_combination

**Comment by jrbray1** [comment]
Does editing a bench still add one to your score and reduce it by one for the owner, which I never liked. Better to have a separate visited score incremented by a Me Too
 button. System is so open to abuse it should not be prominent.

Cheating is easy anyway, with micro changes to position the easiest. I doubt many care though

**Comment by backache** [comment]
> 
> For example, you added a bench recently which I merged with an existing one - see https://openbenches.org/bench/19184 which has your photo and someone else's.
> 

Ah.. Was that the one where I thought I'd found the motherload just to find some mother had captured a load? :-) 

I was just suggesting extending the gamifction to mean that even if the found one that had already been bagged you left feeling like you contributed

**Comment by backache** [comment]
Oh well

**Comment by edent** [comment]
> Does editing a bench still add one to your score and reduce it by one for the owner, which I never liked. Better to have a separate visited score incremented by a Me Too

Not any more. Your leaderboard positions are safe :-)

However, if I merge two benches, only the original uploader gets the point.

There's also no way for you to lose a photo you've uploaded (unless I delete it / a bench) - even if benches are merged, the photo is still assigned to you. So that's perhaps a better reflection of who is in the lead.

But - please remember - this is just a bit of fun. You cannot exchange these points for anything useful. They are not recorded on the BlockChain. They are not a reflection of how good a person you are 😄

**Comment by jrbray1** [comment]
But "world's greatest bencher" is how I introduce myself at parties!

**Comment by edent** [comment]
> Ah.. Was that the one where I thought I'd found the motherload just to find some mother had captured a load? :-)

Probably 😄 It happens quite a lot. That's why I built the duplicate detector. There are currently 935 duplicate entries which have been merged.

This one - https://openbenches.org/bench/14486 - has been found by three different people.

> I was just suggesting extending the gamifction to mean that even if the found one that had already been bagged you left feeling like you contributed

You still get points on the leaderboard for adding new photos. Updates are always welcome!
