### ISSUE TITLE
Check for duplicates before adding

### ISSUE THREAD

**Issue by summerbeth** [openbenches/openbenches.org#5]
As a contributor I want to check if a bench record already exists before creating a new record.

**Comment by arizonagroovejet** [comment]
This is already possible, isn't it? Assuming people don't get carried away with the unicode possibilities and enter text using sᴍᴀʟʟ ᴄᴀᴘs because that's what's on the inscription, people can easily check if a bench has been submitted already by putting put a bit of the inscription in to the search field on the front page. Although evidently someone didn't realise that
https://openbenches.org/search/?search=Charlotte+Mary+Yonge

Maybe duplicate an instance of the Search Inscriptions input at the top of https://openbenches.org/add/  

Or maybe rather than adding another field to /add/ for searching, put a button next to the Inscription: textarea which when clicked searches the database for whatever text has been entered so far. That way people don't have to type the text one place to check if it's been submitted already and then type it again or copy/paste (if they think of that) it in to somewhere else to submit it. Results of the search could be displayed immediately under the textarea. (Would need to strip line breaks out. Would search results shown on /add/ need to include the address? It'd be neater if they didn't include it. What are chances of two benches in different locations having the same inscription?)

**Comment by arizonagroovejet** [comment]
Maybe typing in the Inscription textarea could automatically trigger a search on entry of every Nth character. N would need to be at least  20. Lots of inscriptions start "in memory of" or "in loving memory of".

**Comment by edent** [comment]
There's also the problem that these two strings are different:

`In memory of Bob`

and

```
In memory of
Bob
```

I *think* the way to do it is...

1. When the user attaches the first image, look up the coordinates and return all benches within a 20m radius (to allow for GPS error).
2. Display captions of nearby benches.
3. Let the user add photos to existing benches, if they are of the same bench.
4. If not, carry on adding.

So the new add screen will be

* Photo
   * nearby benches
* Caption
* Optional other photos

Still thinking though.

**Comment by arizonagroovejet** [comment]
Sounds plausible. May not work elegantly in high bench density areas like
https://openbenches.org/#51.50960/-0.1462099/17

Your mention of line breaks makes me realise that the current Search Inscriptions function doesn't deal with those
 
https://openbenches.org/search/?search=This+Seat+Is+Dedicated+to+The+Cheshire+Regiment+Servicemen
returns no results, but
https://openbenches.org/bench/210/

I guess someone's most likely to put in a few contiguous relevant words, like a name. But maybe the name is split over two lines. 

Looks like it might be possible to do SQL queries that ignore line breaks
https://stackoverflow.com/questions/24268950/how-to-query-without-any-line-breaks-within-fields-and-records-in-oracle
My SQL skills are negligible.

Would it be useful queries were done with what I want to call collapsed whitespace but I'm not sure if I just made that term up? I.e. A search for "foo bar" should return an inscription that contains "foo  bar".

**Comment by edent** [comment]
@arizonagroovejet yup - can you raise that as a new issue and I'll look into it.

**Comment by arizonagroovejet** [comment]
> When the user attaches the first image, look up the coordinates and return all benches within a 20m radius (to allow for GPS error).

In my experience, which I'm sire is not unique, the discrepancy between the coordinates in the photos can sometimes be out by more than 200m yet alone 20m. The look up would need to be done as 20m around where the marker is on the map, updated after every drag of the marker.

**Comment by arizonagroovejet** [comment]
FWIW, I found this about selecting things from a database within a specified distance of a point
https://www.movable-type.co.uk/scripts/latlong-db.html

This step
> 3. Let the user add photos to existing benches, if they are of the same bench.

could perhaps be handled as simply as having some text that says to click on an entry in the list produced in step 2 to go to that bench's page and use the "Edit this bench" button if so desired.

Maybe it would be useful to have some text on the Add page along the lines of "We've got quite a lot of benches now, so it's worth searching before submitting. You can find benches near your current location and search inscriptions [link to front page of site]"  It might save some time/effort both for potential submitters and those fixing duplicates. Like obviously it's great that someone saw this bench https://openbenches.org/bench/6276 and thought of OpenBenches, but it seems a shame that and all their other submissions were duplications.

**Comment by arizonagroovejet** [comment]
Any checking for duplicates needs to take in to account that the same inscription can appear on more than one bench. E.g. these two
https://openbenches.org/bench/8509/
https://openbenches.org/bench/8511/
And as one of those has been detected/entered as 'Mother' and the other as 'mother' I'll also say the checking needs to be case insensitive.

**Comment by edent** [comment]
Fixed in https://github.com/openbenches/openbenches.org/commit/b7d0b917577e3fd633a7a28a47aa36f6b0c1907f

Doesn't alert the user that it is a dupe, but does so in an email to the admin. See https://shkspr.mobi/blog/2020/11/using-soundex-to-find-duplicate-database-entries/
